---
- hosts: webstack
  become: yes
  
  tasks:
    - name: Ensure Apache2 is installed 
      yum:
        name: httpd
        state: latest

    - name: Ensure httpd service is running
      service:
         name: httpd
         state: started 
