
  - name: Ensure Apache2 is installed 
    yum:
      name: httpd
      state: latest

  - name: Ensure httpd service is running
    service:
       name: httpd
       state: started 
  
  - name: Copy the new Index file
    template:
       src: templates/index.j2
       dest: /var/www/html/index.html
    notify:
      - restart_kar
