---
- hosts: localhost
  become: yes

  tasks:
   - name: "To check folder  exists before creating a new"
     stat:
       path: "/home/ec2-user/wah_wah"
     register: register_wah
     tags: folder

   - name: " To create folder"
     file:
       path: "/home/ec2-user/wah_wah"
       state: directory
       owner: ec2-user
       group: ec2-user
       mode: 0755
     when: not register_wah.stat.exists
     tags: folder
   
   - name: "To check file  exists before creating a new"
     stat:
       path: "/home/ec2-user/wah_wah.txt"
     register: register_wahf
     tags: file

   - name: " To create file"
     file:
       path: "/home/ec2-user/wah_wah.txt"
       state: touch
       owner: ec2-user
       group: ec2-user
       mode: 0755
     when: not register_wahf.stat.exists
     tags: file
