---
- hosts: webstack
  become: yes
  
  tasks:
    - name: Ensure Apache2 is installed 
      yum:
        name: httpd
        state: latest

    - name: Ensure httpd service is running
      service:
         name: httpd
         state: started 
    
    - name: Copy the new Index file
      template:
        src: template/index.html
        dest: /var/www/html/index.html
        notify: restart_kar
             
  handler:
    - name: restart_kar
      service: httpd
      state: restarted      