
- name: "To create new folder on {{ansible_hostname}}"
#  debug:
 #   msg: " Checking,,,,,,,"
  file:
    path: "/home/ec2-user/folder_test"
    state: touch
    owner: ec2-user
    group: ec2-user
    mode: 0755
  
#- name: " To  create new empty file"
 # file:
  #  path: "/home/ec2-user/file_test/test.txt"
   # state: touch
- name: "Debug"
  debug:
    msg: "HI"
  
